// Teaches OpenNext's getCloudflareContext() about the bindings declared in
// wrangler.jsonc. `Cloudflare.Env` is generated by `npm run cf:types`, so
// rerun that after adding or renaming a binding.
import type {} from "@opennextjs/cloudflare";

declare global {
  // Empty body is the point: this merges the generated bindings into the
  // interface OpenNext declares, rather than adding members of its own.
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface CloudflareEnv extends Cloudflare.Env {}
}

export {};
